"use client" 
import { Provider } from "react-redux"; 
import "../app/globals.css";
import { store, persistor } from "../ts/store"; 
import type { Metadata } from 'next';
import { PersistGate } from "redux-persist/integration/react";

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
            <PersistGate loading={null} persistor={persistor}>
                {children}
            </PersistGate>
        </Provider>
      </body>
    </html>
  )
}