"use client" 
import { Provider } from "react-redux"; 
import "../app/globals.css";
import store from "../ts/store"; 
// import type { Metadata } from 'next';

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
//     icons: {
//         icon: '/favicon.png',
//     },
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
            {children}
        </Provider>
      </body>
    </html>
  )
}